version: "3.8"

services:
  backend:
    image: jonev/secfit:backend
    volumes:
      - ./db.sqlite3:/code/db.sqlite3

  frontend:
    image: jonev/secfit:frontend

  proxy:
    image: nginx:perl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4011:80
