version: "3.8"

services:
  backend:
    image: jonev/secfit:backend
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
      - ./media:/code/secfit/media
    deploy:
      mode: replicated
      replicas: 2

  frontend:
    image: jonev/secfit:frontend
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2

  proxy:
    image: nginx:perl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4011:80
