# Generated by Django 3.1 on 2021-03-05 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workouts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0003_rememberme'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='users.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExerciseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=workouts.models.exercise_directory_path)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workouts.exercise')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
