# Generated by Django 3.1 on 2021-02-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20210228_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutinvitation',
            name='participant',
            field=models.CharField(max_length=500),
        ),
    ]
