# Generated by Django 3.1 on 2021-02-28 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0006_auto_20210228_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutinvitation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
