# Generated by Django 3.1 on 2021-03-04 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0007_auto_20210228_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='participants',
            field=models.ManyToManyField(related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
