# Generated by Django 3.1 on 2021-03-06 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0008_workout_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
