name: CI/CD
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        env:
          GROUPID: ${{ secrets.GROUPID }}
          DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        with:
          context: ./backend/secfit
          push: true
          tags: jonev/secfit:backend   
      - 
        name: Backend Image digest
        run: echo ${{ steps.docker_build_backend.outputs.digest }}
  
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        env:
          GROUPID: ${{ secrets.GROUPID }}
          DOMAIN: ${{ secrets.DOMAIN }}
          URL_PREFIX: ${{ secrets.URL_PREFIX }}
          PORT_PREFIX: ${{ secrets.PORT_PREFIX }}
        with:
          context: ./frontend
          push: true
          tags: jonev/secfit:frontend   
      - 
        name: Frontend Image digest
        run: echo ${{ steps.docker_build_frontend.outputs.digest }}
        
  deploy:
    needs: [build_backend, build_frontend]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy to Docker swarm
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
        script: /home/${{ secrets.DEPLOY_USERNAME }}/secfit/update
