name: TEST
on:
  push:
    branches-ignore:
     - master
     
  pull_request:
    branches: 
     - '**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build backend
        id: docker_test_backend
        uses: docker/build-push-action@v2
        env:
          GROUPID: ${{ secrets.GROUPID }}
          DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        with:
          context: ./backend/secfit
          push: false
          tags: jonev/secfit:backend-test
      - 
        name: Backend Image digest
        run: echo ${{ steps.docker_build_backend.outputs.digest }}
      
      - 
        name: Test backend
        uses: addnab/docker-run-action@v2
        with:
          image: jonev/secfit:backend-test
          run: |
           echo "Starting testing"
           coverage run --source='.' manage.py test
           coverage report
